language: go

go_import_path: github.com/adoptopenjdk/jlink.online

go:
  - 1.14.x

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
