
name: Docker

on:
  push:
    branches:         
    - master

jobs:
  build-and-push-jlink:
    name: jlink.online
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Push to OpenShift
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.OPENSHIFT_USERNAME }}
        password: ${{ secrets.OPENSHIFT_TOKEN }}
        registry: registry.pro-us-east-1.openshift.com
        repository: jlink-online-production/jlink-online
        tags: latest
        push: ${{ github.ref == 'refs/heads/master' }}
