name: "Test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build and Test on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.4

    - uses: actions/checkout@v2

    - name: Test
      run: |
        go test -coverprofile coverage.txt -covermode atomic

    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        fail_ci_if_error: true
